# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155f4196fed3566a2506428a0aec5b38ef2ccc188d8fa57e17230660f419f3366d7203798370148e975e5c4dee947598d51027231607bae2083aed9c74f3c7cb

test:
  secret_key_base: 372f96feabd54a0b3726a06ac2976d34cc1c3597496f6b12acccb7167443d747ec0ab08604ca0d8a3e01136931318eb9febfca739446ce5a7b27356bd3948977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
